version: '3'
services:
  nginx-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-80}:80
      - ${ADMIN-PORT-81}:81
      - ${HTTPS_PORT:-433}:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt